# Generated by Django 3.2 on 2021-05-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210507_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='interview_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='interview_method',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reply_act',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='response_act',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
